const countries = {
  "ar": { name: "Argentina", code: "ar" },
  "au": { name: "Australia", code: "au" },
  "at": { name: "Austria", code: "at" },
  "be": { name: "Belgium", code: "be" },
  "br": { name: "Brazil", code: "br" },
  "bg": { name: "Bulgaria", code: "bg" },
  "ca": { name: "Canada", code: "ca" },
  "cn": { name: "China", code: "cn" },
  "co": { name: "Colombia", code: "co" },
  "cu": { name: "Cuba", code: "cu" },
  "cz": { name: "Czechia", code: "cz" },
  "fr": { name: "France", code: "fr" },
  "eg": { name: "Egypt", code: "eg" },
  "de": { name: "Germany", code: "de" },
  "gr": { name: "Greece", code: "gr" },
  "hk": { name: "Hong Kong", code: "hk" },
  "hu": { name: "Hungary", code: "hu" },
  "in": { name: "India", code: "in" },
  "id": { name: "Indonesia", code: "id" },
  "ie": { name: "Ireland", code: "ie" },
  "il": { name: "Israel", code: "il" },
  "it": { name: "Italy", code: "it" },
  "jp": { name: "Japan", code: "jp" },
  "lv": { name: "Latvia", code: "lv" },
  "lt": { name: "Lithuania", code: "lt" },
  "mx": { name: "Mexico", code: "mx" },
  "nl": { name: "Netherlands", code: "nl" },
  "nz": { name: "New Zealand", code: "nz" },
  "ng": { name: "Nigeria", code: "ng" },
  "no": { name: "Norway", code: "no" },
  "ph": { name: "Philippines", code: "ph" },
  "pl": { name: "Poland", code: "pl" },
  "pt": { name: "Portugal", code: "pt" },
  "ro": { name: "Romania", code: "ro" },
  "ru": { name: "Russia", code: "ru" },
  "kr": { name: "S. Korea", code: "kr" },
  "sa": { name: "Saudi Arabia", code: "sa" },
  "rs": { name: "Serbia", code: "rs" },
  "sg": { name: "Singapore", code: "sg" },
  "sk": { name: "Slovakia", code: "sk" },
  "si": { name: "Slovenia", code: "si" },
  "za": { name: "South Africa", code: "za" },
  "se": { name: "Sweden", code: "se" },
  "ch": { name: "Switzerland", code: "ch" },
  "tw": { name: "Taiwan", code: "tw" },
  "th": { name: "Thailand", code: "th" },
  "tr": { name: "Turkey", code: "tr" },
  "ae": { name: "UAE", code: "ae" },
  "gb": { name: "UK", code: "gb" },
  "ua": { name: "Ukraine", code: "ua" },
  "us": { name: "USA", code: "us" },
  "ve": { name: "Venezuela", code: "ve" },
}

export default Object.freeze(countries)